# Generated by Django 4.2.11 on 2026-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a local jpeg/png image file', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an external image link', max_length=500, null=True),
        ),
    ]
